HAI 1.2
    I HAS A PRICE
    I HAS A HRS2
    I HAS A HRS
    VISIBLE "HAI MUM, WELCOME TO PRISION! HAVE A CALL UWU!"
    VISIBLE "SO UH HOW MUCH HRS YOU CALLIN'? "
    GIMMEH HRS

    BIGGR OF HRS AN 2
    O RLY?
        YA RLY
            HRS2 R DIFF OF HRS AN 2
            PRICE R PRODUKT OF HRS2 AN 0.5
            PRICE R SUM OF PRICE AN 2.5
        NO WAI
            PRICE R PRODUKT OF TIME AN 1.25
    OIC

    VISIBLE "OKI YA PAYIN " PRICE " FOR DIS CALL."
KTHXBYE